#ifndef _TEST_PARAM_CONFIG_H_
#define _TEST_PARAM_CONFIG_H_

#define MQTT_SERVER_ENDPOINT   "PLACE_HOLDER"
#define MQTT_SERVER_PORT       (8883)

#define ECHO_SERVER_ENDPOINT   "PLACE_HOLDER"
#define ECHO_SERVER_PORT       (8000)

#endif /* _TEST_PARAM_CONFIG_H_ */
